### ISSUE TITLE
IE11 Promise Issue

### ISSUE THREAD

**Issue by bhardy** [contentful/contentful.js#136]
We're grabbing contentful.js with an ajax call, and then creating a client and doing a `client.getEntries`. It's working perfectly in every browser we support except in IE11 where I get an error from contentful.js that `'Promise' is undefined`. 

This only happens in IE11. I understand that IE11 doesn't support ES6 promises, but I don't see anyone else having this issue or any mention of polyfilling es6-promises in the documentation.

Is there a workaround? Should I simply fire the es6-promises polyfill first?

Thanks

**Comment by bhardy** [comment]
Update: Adding the es6-promise polyfill (https://www.npmjs.com/package/es6-promise) fixes the issue. If it is required you should make a note in the documentation. If not, let me know!

**Comment by axe312ger** [comment]
Hey Brandt,

for this reason we implemented the es-promise module on our own, so you do not have to polyfill. 
I am currently investigating why this happens and our tests didn't catch it.

Cheers,
Benedikt

**Comment by axe312ger** [comment]
@bhardy
Thanks for reporting this nasty error. Since the error is caused by a dependency ([axios](https://github.com/mzabriskie/axios#promises)) we can not ponyfill it.

Polyfilling as a library is a no go, so I added a hint to our readme, that polyfilling is required when u want to use the IE11. (https://github.com/contentful/contentful.js/commit/7ef344d3446e0437990580f81214aca38dc298d7)

In a later step, we will remove es6-promise in our own dependencies, that will slim the bundle size by more than 20kb for everybody :)

Sorry for the trouble,
Benedikt

**Comment by bhardy** [comment]
@axe312ger Thanks for the quick reply. I'm happy to help.
