### ISSUE TITLE
not found on bower

### ISSUE THREAD

**Issue by refaelos** [contentful/contentful.js#149]
I tried installing contentful from bower but it's not found:

```
$ bower install contentful
bower                        ENOTFOUND Package contentful not found
```

Any idea why?

**Comment by axe312ger** [comment]
All releases since v3.0.0 were broken on Bower, because Bower seems to distribute plain copies of the src directory which results in a missing `dist` directory with the transpiled, minimized and optimized files missing. This means about 1.5 years of faulty releases on Bower, which should be resulted in a broken dependency for a big majority of the users.

That's why I removed them yesterday, our plan is to continue supporting a CDN link, npm and yarn, as we mention in the readme. Bower might be supported at a later state of the library, but looks like Bower itself is slowly resigning. On their website, it says:
> ...psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects!

It is also possible to combine Bower and npm in the project toolchain, even when it is recommended to completely switch to npm. Every frontend project nowadays is available on npm, switching away from Bower should only take a few minutes. If you need help there, let me know.

Hope this did answer your question in an acceptable and comprehensible way.

All the best,
Benedikt

**Comment by refaelos** [comment]
Ok thanks!
