### ISSUE TITLE
XMLHttpRequest is not defined inside Webpack

### ISSUE THREAD

**Issue by filiphazardous** [contentful/contentful.js#169]
* **Node Version**: v8.0.0
* **Npm Version**: 5.0.3
* **Platform**: Darwin MacBook-Pro.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
* **Package Version**: 4.1.2 and 4.5.0

I have a simple webpack project, where my plan is to build a static website populated with data fetched from contentful. However, fetching data results in the following error:

ERROR in ReferenceError: XMLHttpRequest is not defined
    at dispatchXhrRequest (evalmachine.<anonymous>:1815:19)
    at Promise (<anonymous>)
    at xhrAdapter (evalmachine.<anonymous>:1807:10)
    at dispatchRequest (evalmachine.<anonymous>:4115:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)

This looks like the same error as in issue #131 - so I tried both @latest and @4.1.2 (which has the fix #132), but no cigar.

Attaching the offending webpack config and referenced index.js

[index.js.txt](https://github.com/contentful/contentful.js/files/1107824/index.js.txt)
[webpack.config.js.txt](https://github.com/contentful/contentful.js/files/1107823/webpack.config.js.txt)

**Comment by axe312ger** [comment]
Hey Filip,

which version of webpack are you using? Between 1, 2 and 3 are huge differences. You config looks like webpack 1 but I am not sure.

Thanks,
Benedikt

**Comment by axe312ger** [comment]
Anyways, I guess the problem here is again the require logic of Axios :/

Can you try to set the following config for webpack to `['module', 'main']`
https://webpack.js.org/configuration/resolve/#resolve-mainfields (Webpack 2 + 3)
https://github.com/webpack/docs/wiki/configuration#resolvepackagemains (Webpack 1)

This might help since you will force it to require the es6 modules version instead of our UMD browser bundle.

**Comment by filiphazardous** [comment]
Thanks for the quick response!
I tried setting resolve.mainFields to `['module', 'main']`, and that leads to another error:
`ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in '/Users/filipjoelsson/projects/vtv/website/node_modules/contentful/dist'`

I am running webpack 3 BTW. My setup is very simple so far, it mostly builds on an example from StaticSiteGeneratorPlugin

**Comment by axe312ger** [comment]
What is the target of the bundle? Will the bundle contain the code generating your page or is the bundle some JS you want to run ON the website?

In the later case, your setup should have been correct in the first place.

https://github.com/contentful-labs/file-upload-example is basically doing what you are doing, just with the contentful-management.js

I'll give it a try with the CDA, maybe sth in our UMD build of the CDA is different to the UMD in the CMA.

Also, due to crazy stuff in Axios, you can't really use the same file from our repository for node and the browser :/

**Comment by filiphazardous** [comment]
The bundle contains the code generating my page. Right now I'm working around the issue by fetching my content with cURL as a first build-step as a work-around.

**Comment by axe312ger** [comment]
We had the same issues when trying to create a UMD bundle for browser and node. 

It may help when u set the target to `node`, to tell Axios to only include node related code. But I am not sure if this will work.

I tried several workarounds with the snippet and webpack config you provided. But had no luck to get it running.

The problem here is that `static-site-generator-webpack-plugin` requires `umd` libraryTarget, which feels weird to me since the code should run via node, not in the browser.

From here on, I guess I can't help you more, the static site generator plugin is not compatible with our SDK. We are already discussing to get rid of axios since it also caused other problems. But this will take time.

Till we fixed that by replacing a dependency, you might give these static site generators a try:
* https://github.com/contentful/contentful-metalsmith
* https://github.com/gatsbyjs/gatsby/tree/1.0/examples/using-contentful (comes with V1.0 which is released very soon)
* https://github.com/contentful/blog-in-5-minutes

Any input how to fix the issue is welcome, I am very happy to apply a hotfix to our SDK's or vote up any issue on the axios repository :)

Benedikt

**Comment by filiphazardous** [comment]
Thanks for the effort!
I'll get back if I find a solution myself, otherwise I'll just keep working around the problem.

**Comment by axe312ger** [comment]
Alright. Let me know if you found sth :)

**Comment by Wimmind** [comment]
@filiphazardous hi, you solved this problem?
