### ISSUE TITLE
Rate limit error occurred. Waiting for 1698 ms before retrying....

### ISSUE THREAD

**Issue by gauravmishra24** [contentful/contentful.js#175]
Hi Team,

I have tried to fetch the details through Contentful Delivery API but getting error "Rate limit error occurred. Waiting for 1698 ms before retrying....".

We have already updated our Contentful package to version 4.3.0 but still facing this issue while fetching the contents.

Below are the version and package details-:
Node version- 6.10.3
Npm Version- 3.1.10
Package- contentful
Package Version- 4.3.0

Please have a look at this issue as this is hindering the deliveries and let me know if some further information is required.

**Comment by axe312ger** [comment]
Hey Gaurav,

this should only be displayed when u hit the rate limits of your account, also, after the waiting time, it should do the request again and just work.

But, there was a bug in the past, which caused an unlimited retry. To fix this, you need to have a more up to date version of `contentful-sdk-core`.

Lock files can cause this issue since they keep the version of `contentful-sdk-core` as long it matches the minimum version instead of loading the newest version on `npm install`.

Can you try to delete your node_modules and you lock files and run `npm install` again? This should fix the issue.

All the best,
Benedikt

**Comment by axe312ger** [comment]
An option to disable retrying was released in Juli. Closing this ticket due to inactivity.
