### ISSUE TITLE
Library size 330 Kb 🤔

### ISSUE THREAD

**Issue by katspaugh** [contentful/contentful.js#177]
For a script that issues Ajax requests and resolves links in the resulting JSON, 330 Kb seems _a bit_ like an overkill.

Any idea what inflates the size of the library? Is it Axios?

**Comment by axe312ger** [comment]
Wow already 3 👍   :D 

Did you see https://github.com/contentful/contentful.js/pull/174? We are working on it. I got the contentful.js now locally down to 17kb (gzipped)

We replaced lodash and yes, the last big dependency is Axios.

Sadly it is not that trivial to replace axios, especially since we have to take care the SDK is working in browser and node.

**Comment by axe312ger** [comment]
Also, we will then provide an es modules version which allows you to use tree shaking with webpack and similar tools :)

**Comment by katspaugh** [comment]
> Wow already 3

Yeah, I asked co-workers to chime in 😬

OK, great! We'll try the es-modules version. Maybe mention that in the [Readme](https://github.com/contentful/contentful.js#using-es6-import)?

Excited to see the outcome of #174, too. Thanks!

**Comment by axe312ger** [comment]
@katspaugh simply cus the current version only contains bundled version. I can update u as soon i pushed the first beta of the new major version including a modules target :)

**Comment by axe312ger** [comment]
Just for your information, there are now release candidates on npm which you might test. I have incredible improvements in our own example apps.

install via `npm install contentful@next`

**Comment by katspaugh** [comment]
It looks very good ! With the next branch, I only see `axios` (35 Kb), `contentful-sdk-core` (11 Kb) and `contentful` itself (~30 Kb). Nur weiter so! 👍
