### ISSUE TITLE
Property 'EMBEDDED_RESOURCE' does not exist on type 'typeof BLOCKS'

### ISSUE THREAD

**Issue by davidruisinger** [contentful/contentful.js#1953]
## Possible Solution

Temporarily solution is to set resolutions in package.json to:
```
"resolutions": {
  "@contentful/rich-text-types": "16.2.0",
}
```

Clean solution is to upgrade the `@contentful/rich-text-types` dependency in this package's package.json.

## Context

Typescript complains that `EMBEDDED_RESOURCE` does not exist on type `typeof BLOCKS` which is used as a property [here](https://github.com/contentful/contentful.js/blob/c45fcffceaec50cb6896be56441f5162169a684f/lib/types/content-type.ts#L95).
Looking at the commit [here](https://github.com/contentful/rich-text/commit/c85fd632d5166bf6a4bd30adbc3ed35668f2e7d5) I can see, that it has been recently added but this package is still referencing the outdated version in package.json.

## Environment

-   **Language Version**: 18.6.0
-   **Package Manager Version**: 9.5.1
-   **Operating System**: Unix 64 Bit
-   **Package Version**: 10.3.1
-   **Which API are you using?**: Delivery

**Comment by veu** [comment]
If I create a new project and install contentful.js with version 10.3.1 it installs `rich-text-types` with version `16.2.0` because that’s what’s defined in the `package-lock.json`.

There must be something else at play here but it’s hard to debug remotely. 🤔  Do you see anything else in your project’s package-lock.json or any error when running `npm install`.

**Comment by davidruisinger** [comment]
@veu you're right. Something got messed up in my `yarn.lock` file. All good now 🙏🏻
