### ISSUE TITLE
Angled brackets in code blocks are dropped

### ISSUE THREAD

**Issue by claudiahub** [contentful/contentful.js#2004]
## Context
In the markdown editor, when using any code block formatting type, it’s not possible to render any angled bracket to be visible in the Preview editor.

## Expected Behavior
The angled brackets are rendered correctly within the preview editor. 
## Actual Behavior
- Open any Contentful markdown editor instance
- Insert a code block element
- Write any angled bracket symbol placing it inside the code block
- Click on preview 
- Result: angled brackets are dropped.  

Please see below screenshots 
- pic.1: html editor 
- pic.2: preview showing angled brackets being dropped 
<img width="757" alt="Screenshot 2023-08-31 alle 15 09 37" src="https://github.com/contentful/contentful.js/assets/54085737/aa8c0b91-1d61-4411-abf6-3960f39cd618">
<img width="754" alt="Screenshot 2023-08-31 alle 15 10 04" src="https://github.com/contentful/contentful.js/assets/54085737/45f7ddde-bf27-4875-8800-97492fbd7003">

## Environment
* Language Version: Node v17.9.1
* Browser: Chrome v16.0.5845.140
* Gatsby: 4.24.1
* Typescript: 4.8.4 
* Which API are you using?: Delivery

**Comment by schauder** [comment]
When the final page is rendered angled brackets seem to get rendered correctly. See for example the first code block here: https://spring.io/blog/2023/08/31/this-is-the-beginning-of-the-end-of-the-n-1-problem-introducing-single-query

So, to me this seems to be an issue of the different preview renderers.

**Comment by claudiahub** [comment]
@schauder thanks Jens, I've updated the reproduction steps 👍

**Comment by tpkahlon** [comment]
Hello Claudia,

Preview mode doesn't display angle brackets because Markdown's code block formatting is designed to display code as plain text, not as HTML or other markup. That's why angled brackets (used for HTML tags) and other special characters within code blocks are not rendered as they would be in normal text. 

To mimic angle brackets as code block formatting type, in the `Editor` mode, you can use `less than` and `greater than` symbols:

```
angled brackets: &lt;anyCode&gt;
```

**Comment by claudiahub** [comment]
@tpkahlon Hi Tej, 

I've already applied the `less than` and `greater than` symbols.

Both of them, `&lt;` and `&gt;` are rendered as html entities in the preview editor, not as you would see them as a HMTL tag without &....; .

Please see my screenshots 

(Screen 1) editor mode with mentioned above symbols.

(Screen 2) result rendered in preview mode.

Thank you.

<img width="753" alt=" editor-mode-symbols-added" src="https://github.com/contentful/contentful.js/assets/54085737/c223c339-50ed-4d26-b529-381cf19405a9">

<img width="764" alt="preview-mode-symbols-dropped" src="https://github.com/contentful/contentful.js/assets/54085737/2cf7192e-b778-4e32-a713-1d1376f6b8b0">

**Comment by tpkahlon** [comment]
Hello Claudia,

Could you please share the full configuration of the body field in your content model? This would greatly assist in reproducing the issue on our end and addressing it as soon as possible.

**Comment by tpkahlon** [comment]
I can reproduce the issue. Angle brackets disappear when you create a space or tab in front of text. If you don't add a space or tab before the text, angled brackets remain preserved.

**Comment by claudiahub** [comment]
@tpkahlon here's the config for the field as it is on the content model.
`{
      "id": "body",
      "name": "Body",
      "type": "Text",
      "localized": false,
      "required": false,
      "validations": [],
      "disabled": false,
      "omitted": false
    }`
It seems the issue is still happening because any code block element in the editor, adds automatically a tab before the code text. 
Since the issue to us depends on code blocks usage, we're still seeing it.

**Comment by tpkahlon** [comment]
Hello @claudiahub,

I've thoroughly reviewed the issue you raised and have some information to share.

You're absolutely right about the problem. When you use code block formatting in the Markdown editor and add custom code, it removes angled brackets in the preview mode.

After investigating, I can confirm that your custom code with angled brackets will remain intact in the API data and can be correctly displayed on the page or site.

In the Markdown preview tab, the editor uses a sanitizer package behind the scenes to prevent cross-site scripting (XSS) attacks. It carefully processes all the text you input before displaying it in the preview mode. The [DOMPurify package](https://www.npmjs.com/package/dompurify), which is responsible for this, flags text with angled brackets and custom code inside them as potentially malicious because it can't verify them as valid HTML markup. This is why `ampersands` and angled brackets (`less than` and `greater than`) symbols are removed by the parser.

If you want to preview a piece of code in a code block format, I recommend using valid `HTML`, `SVG`, or `MathML` code. These markups are allowed by the package.

However, if you wish to preview custom code in a different language in the Preview mode, it might be possible to disable text sanitization in the [Field Editors mono-repo](https://github.com/contentful/field-editors/tree/master). Please note that this approach may not be accepted by the team as it could increase the risk of XSS attacks.

To verify these conclusions, I've outlined steps for you to test sample case (disabling text sanitization) yourself:

- Clone the [fields-editor mono-repo](https://github.com/contentful/field-editors/tree/master) to your local environment.
- Open the `markdown` package folder and disable the `cleanHTML` function in the file: `packages/markdown/src/components/MarkdownPreview.tsx`, specifically on line `205`. Instead, render `props.value` in place of `cleanHTML` on line `225` within the JSX markup for this file.
- Run the package locally. To test, Enter custom code with angled brackets in the Editor mode, and you should be able to preview angled brackets in Preview mode.

**Comment by marcolink** [comment]
This issue seems to be solved. Closing it for now. Please feel free to re-open it again. 
Additionally, you can always join our [community discord](https://www.contentful.com/discord/).
