### ISSUE TITLE
EntryFieldTypes.AssetLink Type not working as expected

### ISSUE THREAD

**Issue by matgott** [contentful/contentful.js#2138]
```
export interface BlogPostFields {
  title: EntryFieldTypes.Symbol;
  publicationDate: EntryFieldTypes.Date;
  slug: EntryFieldTypes.Symbol;
  featuredImage: EntryFieldTypes.AssetLink;
  description: EntryFieldTypes.Symbol;
  content: EntryFieldTypes.RichText;
  featured?: EntryFieldTypes.Boolean;
}

export type BlogPostSkeleton = EntrySkeletonType<BlogPostFields, "blogPost">;
export type BlogPost = Entry<BlogPostSkeleton, undefined, string>;
```

I have my Blog type with the `featuredImage` prop that I want to access when I get the entries:
```
const posts = contentfulClient.getEntries<BlogPostSkeleton>({
  content_type: "blogPost",
});
```

## Expected Behavior
`posts.items[0].fields.featuredImage` has all AssetLink props

## Actual Behavior
`posts.items[0].fields.featuredImage` only has `sys` prop (missing fields and metadata)

![image](https://github.com/contentful/contentful.js/assets/16677716/af7aa47f-f3a3-4cb7-bd34-19d40f9fa7a5)

**Comment by matimyrTSH** [comment]
bump, facing the same issue

**Comment by AndyJones1989** [comment]
Bump, this is giving me a right headache.

**Comment by marcolink** [comment]
Hey, 
if you log `posts.items[0].fields.featuredImage`, do you get the full payload, org just the link object?

**Comment by matgott** [comment]
> Ah, this might not be intuitive, but I think it should be
> 
> ```
> export type BlogPost = Entry<BlogPostSkeleton, 'WITHOUT_UNRESOLVABLE_LINKS', string>;
> ```

Not sure about this but I added it and it is the same :/

**Comment by matgott** [comment]
> Ah, this might not be intuitive, but I think it should be
> 
> ```
> export type BlogPost = Entry<BlogPostSkeleton, 'WITHOUT_UNRESOLVABLE_LINKS', string>;
> ```

Thanks man, that was the thing. Is there any docs or reference to this generic argument?

**Comment by AndyJones1989** [comment]
Yeh, this worked for me too (and has enabled me to avoid quite a bit of casting in other files too). Definitely needs to be included in the Typescript docs linked to the v10 migrations page.

**Comment by marcolink** [comment]
Here is a little run down of what I have in my head:

The types you shared are meant to be passed in as generics for the client methods. depending on the chain modifiers, the response types are different. Let me try to outline some ways to get the right response types:

Let's assume we have a client instance created. In my case, we already define a chain modifier:
```ts
const contentfulClient = createClient({
  space: SPACE,
  accessToken: TOKEN,
}).withoutUnresolvableLinks
```
This client instance, will only return entries, where links can be resolved (relevant for the response types)

**Infer from client method**
One way to get the right response type based on the provided content type is to Infer the type directly from the client method. We can create a little util type for that: 

```ts
type InferResponseType<T extends EntrySkeletonType<FieldsType, string>> = Awaited<ReturnType<typeof contentfulClient.getEntries<T>>>
```
We can now use this type, to create response types for our input types:

```ts
const BlogPostResponseType = InferResponseType<BlogPostSkeleton>
```
The response type is now inferred but the return type of client method `getEntries`, on a chained client with the modifier `withoutUnresolvableLinks`. This automatically creates a return type, where it's guaranteed that all links are resolved. 

This would become a valid assignment:
```ts
const blogPost: BlogPostResponseType = await contentfulClient.getEntries< BlogPostSkeleton >({
    include: 10,
    locale: 'en-US',
    content_type: 'blogPost',
  })
```

**Alternative way:**
Instead of directly inferring from the client method, we can create another util type: 

```ts
export type WithoutUnresolvableResponse<T extends EntrySkeletonType<FieldsType, string>> = Entry<T, 'WITHOUT_UNRESOLVABLE_LINKS', string>;
```

This again allows to easily create the the right response types:

```ts
const BlogPostResponseType = WithoutUnresolvableResponse<BlogPostSkeleton>
```

In this case, we just have to be sure, that the manually create response type, is matching the used modifiers on the called client method.  

**Different `ChainModifier` values**
When we want to manually define the response type, we can define a string union for the ChainModifier template. 
Possible values are: 

- `WITH_ALL_LOCALES` all fields are returned in all languages
- `WITHOUT_LINK_RESOLUTION` no links are resolved, all link objects stay as they are
- `WITHOUT_UNRESOLVABLE_LINKS` avoid mixed shapes, if a link can't be resolved, the field get's removed
- `undefined` currently not sure what this resolves to 🤔 

When we want to manually craft return types, we have to ensure we match the used `ChainModifers` on the client:

```ts
const contentfulClient = createClient({
  space: SPACE,
  accessToken: TOKEN,
})

//client chained with `withAllLocales` modifier
const blogPost = await contentfulClient.withAllLocales.getEntries()
type BlogPostResponse = Entry<BlogPostSkeleton, 'WITH_ALL_LOCALES', 'en-US' | 'de-DE'>

//client chained with `withAllLocales` AND `withoutUnresolvableLinks` modifier
const blogPost = await contentfulClient.withAllLocales.withoutUnresolvableLinks.getEntries()
type BlogPostResponse = Entry<BlogPostSkeleton, 'WITH_ALL_LOCALES' | 'WITHOUT_UNRESOLVABLE_LINKS', 'en-US' | 'de-DE>

I hope that makes it a bit more clear :) 

@mgoudy91 maybe we can add this to the docs?

**Comment by marcolink** [comment]
The generation of response types is now possible with [cf-content-types-generator@2.15.0](https://github.com/contentful-userland/cf-content-types-generator)
