### ISSUE TITLE
import contentful from 'contentful' changed behaviour

### ISSUE THREAD

**Issue by grncdr** [contentful/contentful.js#42]
When we moved to ES6, users of this library who are _also_ using Babel get subtly different behaviour when importing. Now when you `import contentful from 'contentful'` you don't get an object containing all exported functions, but rather the (non-existant) `default` export from this library. We need a backwards compatible `export default` statement.

**Comment by wmadden** [comment]
@grncdr related to this topic, users who're compiling Contentful from source will also be hit by the ["bug" in axios](https://github.com/mzabriskie/axios/issues/44) that it imports and forcefully polyfills the global Promise implementation with the `es6-promise` polyfill.

This caused problems for us because `es6-promise` won't handle errors that aren't caught in a call to `catch()` at all - they just get eaten.

**Comment by rossthedevigner** [comment]
Just came upon this issue today... `1.1.5`

**Comment by trodrigues** [comment]
Keeping an eye on the next release of axios which will fix the issue.

**Comment by trodrigues** [comment]
Created #44 to track that.

**Comment by trodrigues** [comment]
Fixed on 2.1.0.
