### ISSUE TITLE
Can't filter by multiple content types

### ISSUE THREAD

**Issue by cajoy** [contentful/contentful.js#424]
So I have a problem with filtering results when have mutiple content types,

So for example following 2 queries works fine:

```
  'fields.content.sys.contentType.sys.id[in]': ['customerIndividualPage'],
  'fields.industry[in]': 'Automotive'
```

```
  'fields.content.sys.contentType.sys.id[in]': ['customerIndividualPage', 'blogPost'],
```

but it doesn't work when I have filter on industry + multiple content types, it generates an error:

```
  'fields.content.sys.contentType.sys.id[in]': ['customerIndividualPage', 'blogPost'],
  'fields.industry[in]': 'Automotive'
```

`"A Content Type ID is required. When querying for Entries and involving fields you need to limit your query to a specific Content Type. Please send a Content Type ID (not the name) as the URI query parameter \"content_type\"",`

How can I filter by top level field and related model content type?

**Comment by TimBeyer** [comment]
Hi @cajoy,
this is a problem with how the underlying API works.  
In order for you to search based on a field value, the API needs to know the content type to validate whether the field exists, and to scope the query correctly to that field of the entries of that content type.  

The first query works because there is exactly one content type specified and thus the `industry` field can be resolved correctly on the entries of that content type.  

The second query works because no query on a specific field is requested, so the API simply returns all entries of those two content types.

The third query does not work because now the API does not know on which content type to look up the `industry` field.  
Even if both content types were to have an `industry` field, the API insists on a strict 1:1 mapping of CT and field and fails.

So in this case I am afraid you would have to make two separate queries and join the data together on your side.

**Comment by marcolink** [comment]
Closing this for now. Please feel free to re-open it again. Also, the [community slack](contentful-community.slack.com
) is always a good place to ask general questions to our CDA API.
