### ISSUE TITLE
parseEntries "maximum call stack" error caused by circular references

### ISSUE THREAD

**Issue by dndrsn** [contentful/contentful.js#445]
`parseEntries` fails when trying to parse items with circular references.  

In my particular scenario I have an article content type that has references to "related articles" of the same content type.  If article A references article B and article B references article A, using `parseEntries` with either article will result in a `maximum call stack exceeded` type error.

This is related to other circular reference issues (#377, #297), but I believe it is different since it is specific to `parseEntries`.  It happens even if `include` is set to 1.

## Expected Behavior

`parseEntries` to be able to process content data with circular references.

## Actual Behavior

`parseEntries` throws a "maximum call stack exceeded" error when processing data with circular references.

## Possible Solution

Adding an optional "depth" parameter to `parseEntries` might be a solution.

## Steps to Reproduce

1. Create a content type that allows references to the same content type.
2. Create two content items that reference each other.
3. Use `getEntries` to retrieve the content items
4. Use `parseEntries` on the data

## Context

As noted above,  I have an article content type that has references to "related articles" of the same content type.  If article A references article B and article B references article A, using `parseEntries` with either article will result in a `maximum call stack exceeded` type error.

I have been able to work around the issue with the following ... less than ideal solution.

```
const safeStringify = require('fast-safe-stringify');

const removeCircularReferences = obj => JSON.parse(safeStringify(obj));

...

let data = await contentfulClient.getEntries(query);
data = removeCircularReferences(data);
data = contentfulClient.parseEntries(data);
```

## Environment

-   **Language Version**: Node v15.0.1
-   **Package Manager Version**: Yarn 1.22.10
-   **Package Version**: 7.14.8
-   **Which API are you using?**: Delivery

**Comment by TimBeyer** [comment]
Hey @dndrsn,
`parseEntries` is a method that is supposed to be used on the raw responses that come from the delivery API to resolve the references from the `includes` and turn everything into the correct JS objects that have references resolved.  
The idea I suppose being that if you for whatever reason deal with data that has been fetched via the API directly instead of via the SDK - maybe dealing with a separate service that provides the raw responses for further processing - you can still turn the data into the format that the SDK uses.
Behind the scenes it calls `wrapEntryCollection`, which is also called already when using `getEntries`.

So in that sense, the call to `parseEntries` is redundant and fails because at that point the data has already been transformed into a potential circular object structure and attempting to parse it again yields an error.

I feel like this confusion could have been prevented by calling the method something like `parseRawEntryCollection` or  something in that direction, but by now that would be a breaking change which probably should be discussed a bit more.

The docs for `parseEntries` state "Parse raw json data into collection of entry objects.".
Maybe there is something we could do there to clarify the intent a bit better - like explicitly mentioning that this is not needed in case you use the `getEntries` method?

**Comment by dndrsn** [comment]
@TimBeyer thanks for the explanation.  Makes sense now.  Not exactly sure if the docs are unclear or I just misunderstood.  I think it might help to mention something about "data not retrieved via getEntries".
