### ISSUE TITLE
return entry status on get entry methods

### ISSUE THREAD

**Issue by gregdolder** [contentful/contentful.js#55]
Currently you can get an entry by id. We do this and use slug to retrieve the entry.  When retrieving the object, display the entry status (e.g. Draft, Archived etc).  

We use this for preview mode or redirection on archive.  would be nice to do this without a second call.

**Comment by trodrigues** [comment]
Hi there,

this is actually something we want to add but given that we are planning a rebuild of this library very soon, with a new API, we'd rather not add it right away. I'll leave the issue open and will update it when we add this feature.

**Comment by trodrigues** [comment]
I forgot to explain one thing in my previous comment.

contentful.js is the SDK for the Content Delivery API (CDA) and all the entries you get via the CDA are published.

You cannot get entries via this API which are in draft or archived mode, and any published entries with unpublished updates will only have the content of their last published version.

However, you can configure this client to be used with the Preview API via the host property, which shows unpublished or draft content. So having a way to detect the status would only make sense when using the Preview API or if using [contentful-management.js](https://github.com/contentful/contentful-management.js)

Have a look at https://www.contentful.com/developers/docs/concepts/apis/ for more information on the different APIs.

**Comment by trodrigues** [comment]
I'm going to close this because this actually doesn't make sense, even for the Preview API. The Delivery and Preview APIs don't expose information that allows the user to figure out the current state of an entry. This is only possible via the management api. The new [management](https://github.com/contentful/contentful-management.js) SDK to be released later today will have methods for this.
