### ISSUE TITLE
Protocol relative URLs

### ISSUE THREAD

**Issue by florian-milky** [contentful/contentful.js#734]
When getting assets from contentful, their URLs don't have any protocol.
This is causing me an issue with loki and storybook (storybook is built statically, browser is opening local html, assets are fetched with `file://` instead of `http(s)://`).
Overall it seems like it's now rather discouraged to have protocol relative urls?

**Comment by marcolink** [comment]
Hi @florian-milky 👋 
providing these URLs without protocol has been [identified](https://www.paulirish.com/2010/the-protocol-relative-url/) as good practice. I think the challenge you're facing here might be due to the fact that your storybook is not served, but just loaded from the file system. You can either prepend the protocol manually or serve your storybook using something like [serve](https://www.npmjs.com/package/serve).
