### ISSUE TITLE
Is there a way to change underlying Promise implementation?

### ISSUE THREAD

**Issue by kimmobrunfeldt** [contentful/contentful.js#91]
I would prefer if I could change the library to always return [bluebird](http://bluebirdjs.com) promises to get convenient features like `.tap` method. Is there a way to change the default Promise library?

**Comment by Khaledgarbaya** [comment]
Hey @kimmobrunfeldt,

Unfortunately there is no plans on changing to Bluebird's promises since we don't find it necessary at this point for few reasons.
1. Adding extra size to the library 
2. Having so much unnecessary/won't be often used functionalities.

If you really need Bluebird's promises implementation feel free to make a fork and I will be glad to help you and give you guidance on what you need to change.

**Comment by kimmobrunfeldt** [comment]
Hi,

I didn't mean you should change the library to use Bluebird promises. I'm asking for a way to configure how contentful.js constructs the promises. Some libraries provide a way to override the default Promise library used. That way you can still use native promises and don't need to include bluebird which increases bundle size.

As an example:
```js
var BPromise = require('bluebird');

var client = contentful.createClient({
  // ...
  Promise: BPromise
});

// Now client.getEntry('...') would return a Bluebird promise
```

Now we are manually wrapping all native Promises as Bluebird promises in all calls:

```
BPromise.resolve(client.getEntry('...'))
  .tap(() => // do something);
```

**Comment by Khaledgarbaya** [comment]
Hi,
That's sounds like a great idea it is definitely something that I can look into when I have time.
I added a ticket in the projects section. You can follow the progress [here](https://github.com/contentful/contentful.js/projects/1#card-66264) 
Best,
Khaled

**Comment by kimmobrunfeldt** [comment]
Awesome! Thanks :)
