### ISSUE TITLE
Link resolution does not work when retrieving a single entry

### ISSUE THREAD

**Issue by idris** [contentful/contentful.js#95]
[`getEntries` properly resolves links](https://github.com/contentful/contentful.js/blob/28b571be62ce3195077ddae6d76ced9dcc8b88e3/lib/entities/entry.js#L103-L108), but [`getEntry` does not](https://github.com/contentful/contentful.js/blob/28b571be62ce3195077ddae6d76ced9dcc8b88e3/lib/entities/entry.js#L78-L80).

**Comment by Khaledgarbaya** [comment]
Hi @idris ,
That is true link resolution is not possible only if you request data from collection end-point,so that the sdk will get all the items referenced in the entries to be able to make link resolution. getEntry however is requesting only the actual entry and that how our backend works.
If you want to get always link resolution you can request one entry but using getEntries like so:

```js
let entries = client.getEntries({'sys.id':"MY_ENTRY_ID"})
console.log(entries.items[0])
```

Hope That helped.

Cheers,
Khaled

**Comment by hrc7505** [comment]
![image](https://user-images.githubusercontent.com/17545364/38247269-45294974-3762-11e8-95e4-5bbf281e12eb.png)

what should I do if I want all nested links resolvable. You can see in the image the highlighted portion where fields key not available. I used code you have suggested above.
```
let entries = client.getEntries({'sys.id':"MY_ENTRY_ID"})
console.log(entries.items[0])
```

**Comment by Khaledgarbaya** [comment]
Hi @hrc7505,
By default, you will get one level deep links included in the response if you want more you should specify `include` parameter.
your code should be
`let entries = await client.getEntries({'sys.id':"MY_ENTRY_ID", include:3})`
the include parameter can go up to 10

**Comment by hrc7505** [comment]
Thank you @Khaledgarbaya,
