### ISSUE TITLE
Query linked data

### ISSUE THREAD

**Issue by agarwalswapnil** [contentful/contentful.js#98]
Hi,
I have a content model - `Subject`
I have another content model - `Class`
Each `subject` has a `class` as a reference.

I am able to search `subject` on `class` id, such as `fields.class.sys.id=my_class_id.`
Can I query Subject on class name ?
such as, `fields.class.fields.name=my_class_name`

**Comment by Khaledgarbaya** [comment]
Hi @agarwalswapnil ,
Yes that should work also.
Although fields like name they don't guaranty uniqueness because you might put the name twice, it is recommended to use `slug` for example if you don't want to filter based on ids which is sometimes hard to memorise them

Best,
Khaled

**Comment by agarwalswapnil** [comment]
@Khaledgarbaya 

Thanks.
I am infact using `slug`.
Please help me understand, I have two scenarios

**Scenario 1**
`Subject` has one reference of `Class`

`   {
      "id": "class",
      "name": "Class",
      "type": "Link",
      "localized": false,
      "required": true,
      "validations": [
        {
          "linkContentType": [
            "class"
          ]
        }
      ],
      "disabled": false,
      "omitted": false,
      "linkType": "Entry"
    }`
I have multiple slugs to match to, if class slug is equal to any of the searched slugs, I want to include the subject.

fields.class.fields.slug[in]='my_class_slug_1,my_class_slug_2,my_class_slug_3'


**Scenario 2**
`Subject` has multiple references of `Class`
`    {
      "name": "Class",
      "id": "class",
      "type": "Array",
      "items": {
        "type": "Link",
        "linkType": "Entry",
        "validations": [
          {
            "linkContentType": [
              "class"
            ]
          }
        ]
      },
      "validations": []
    }`

I have one slug to match to, if any one class has a slug equal to the searched slug, I want to include the subject.

fields.class.fields.slug='my_class_slug_1'

I can't run any of the above scenarios. Are these possible ?

**Comment by Khaledgarbaya** [comment]
@agarwalswapnil 

Unfortunately using  `fields.class.fields.slug[in]=my_class_slug_1,my_class_slug_2,my_class_slug_3` won't work because the slug is in a reference field and the query engine does not do link resolution, which is a feature on in the SDK (client side), the query will work if you move the slug to the `Subject` ContentType so your query will look like this : `fields.slug[in]='my_class_slug_1,my_class_slug_2,my_class_slug_3`.

This is valid for both of the scenarios.

**Comment by agarwalswapnil** [comment]
@Khaledgarbaya thanks for the info.
So, basically I can do equality/inequality inclusion/exclusion query on the reference fields ?

I didn't understood you "which is a feature on in the SDK (client side)".

**Comment by Khaledgarbaya** [comment]
No you can't, what I meant is that the SDK does the link resolution for you so that's why you are getting the fields of your reference fields, but if you check the RAW JSON response all the reference fields are just and object with `sys` property that describe it

**Comment by BernsteinA** [comment]
@Khaledgarbaya is there documentation on this? E.g. the difference between the `include` parameter on an API call and the client side link resolution performed by the sdk

**Comment by Khaledgarbaya** [comment]
@BernsteinA the SDK does link resolution for you by default when requesting collections or doing initial sync. as for the `include` you can specify it in the query object.
to disable link resolution : 

```js
let client = contentful.createClient({resolveLinks: false})
```

like 

```js
client.getEntries({include: 10})
```

**Comment by Khaledgarbaya** [comment]
you can find reference docs here https://contentful.github.io/contentful.js/contentful/3.7.0/

**Comment by BernsteinA** [comment]
Docs are unclear on the difference / relationship between include and resolvelinks.
Is my understanding correct that setting `include` causes the API to return the entries that are linked to, in an includes array, but any link fields still remain as Links in the json response?
And that resolvelinks resolves these links, such that any link fields in the entries array (returned by the sdk) contain objects instead of just ids?
And that resolvelinks in and of itself does not incur any additional API calls, and is limited by the depth of the include query parameter?
Include refers to the API request and as such has no effect on whether the sdk could return an entry with circular references?

Please confirm my understanding. Thanks.

**Comment by Khaledgarbaya** [comment]
@BernsteinA ,
Everything you said is right except for the `include`, include is  telling the API how deep the Link level you have because a link can also link to other links and so on.

here is some documentations to explain include https://www.contentful.com/developers/docs/concepts/links/

**Comment by BernsteinA** [comment]
Still unclear, sorry. Will have to do some testing:
1. When include is set but resolvelinks is false: does the API put resolved links in place as the value of the relevant field?
2. If include is e.g. 2, but resolvelinks is true, would two entries that link to each other still get me a circular reference in the sdk response, or does it stop after two iterations?

**Comment by Khaledgarbaya** [comment]
ok i will try to explain it better: 
* `resolveLiks` is an sdk only feature it has nothing to do with the API or the data you are receive forn our endpoint.

for `include` let's say you have E1 -> E2 -> E3 and you specify `include : 1` you will get E1 in the items array and E2 in the include array but not E3 because you specified that you want only link level 1.

This is how the json looks like from the api : 

```json
{
  items:[
    {
       sys{
           id: 'E1_ID'
        },
        fields: {
           e2ref: { // only sys property
               sys : {
               }
            }
        }
     }
  ],
  include: [
    {
       sys : { id:"E2_ID" }
       fields { .... E2 fields}
    }
  ]
}
```

by resolving the link I mean rather than letting you searching the include array always to get the fields we take the fields from E2 inside include array and merge them in e2ref so this way you will have `response.items[o].e2ref.fields.fieldNAme`

**Comment by BernsteinA** [comment]
Thank you. That answers question 1 perfectly.
For question 2 above, what if E1 -> E2 and E2 -> E1 ? What would `response.items[o].e2ref.fields.e1ref` look like?

**Comment by BernsteinA** [comment]
Final question: will an item ever be in both items[] and include[] ?

**Comment by Khaledgarbaya** [comment]
1. We do support circular reference, and `response.items[o].e2ref.fields.e1ref` should be `sponse.items[o].e2ref`.

2. includes doesn’t include the entry if it’s present on items

**Comment by Khaledgarbaya** [comment]
I am closing this issue for now if you have more questions please feel free to open a new issue

**Comment by BernsteinA** [comment]
Fine with me. Thanks for the help.
